name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.8


      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./cucumber-report-viewer

      - name: Build site
        run: npm run build
        working-directory: ./cucumber-report-viewer
        env:
          NODE_ENV: production

      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Build failed - dist directory not found"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "❌ Build failed - index.html not found"
            exit 1
          fi
          echo "✅ Build successful - dist directory contains $(ls -la dist | wc -l) files"
        working-directory: ./cucumber-report-viewer

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cucumber-report-viewer/dist
          publish_branch: gh-pages
